//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Bill_Info = new HashSet<Bill_Info>();
            this.Bill_Remove = new HashSet<Bill_Remove>();
            this.Book_Output = new HashSet<Book_Output>();
        }
    
        public int Bill_Id { get; set; }
        public int Employee_Id { get; set; }
        public double Bill_Total_Money { get; set; }
        public int Customer_Id { get; set; }
        public int Bill_Type { get; set; }
        public Nullable<double> Bill_Promotion { get; set; }
        public Nullable<System.DateTime> Bill_Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Info> Bill_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Remove> Bill_Remove { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Output> Book_Output { get; set; }
        public virtual Output_Info Output_Info { get; set; }
    }
}
