//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Input
    {
        public int Input_Id { get; set; }
        public int Employee_Id { get; set; }
        public int Book_Id { get; set; }
        public int Book_Count { get; set; }
        public Nullable<System.DateTime> Input_Date { get; set; }
        public Nullable<double> Input_Price { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
