//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Book_Input = new HashSet<Book_Input>();
            this.Book_Input_Price = new HashSet<Book_Input_Price>();
            this.Book_Output_Price = new HashSet<Book_Output_Price>();
            this.Book_Query = new HashSet<Book_Query>();
        }
    
        public int Book_Id { get; set; }
        public string Book_Name { get; set; }
        public string Book_Author { get; set; }
        public string Book_Theme { get; set; }
        public string Book_Type { get; set; }
        public string Book_Content { get; set; }
        public byte[] Book_Image { get; set; }
        public Nullable<int> Book_Count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Input> Book_Input { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Input_Price> Book_Input_Price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Output_Price> Book_Output_Price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Query> Book_Query { get; set; }
    }
}
