//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Info
    {
        public int Employee_Info_Id { get; set; }
        public int Employee_Id { get; set; }
        public System.DateTime Date_Start { get; set; }
        public Nullable<int> Sum_Date { get; set; }
        public Nullable<int> Date_In_Month { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
