//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluate
    {
        public int Evaluate_Id { get; set; }
        public int Customer_Id { get; set; }
        public int Employee_Id { get; set; }
        public Nullable<int> Evaluate_Content { get; set; }
        public Nullable<System.DateTime> Evaluate_Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
