//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary_Bonus
    {
        public int Bonus_Id { get; set; }
        public string Bonus_Name { get; set; }
        public Nullable<double> Bonus_Money { get; set; }
    }
}
